# suppress inspection "UnusedProperty" for whole file
server:
  port: 8888
spring:
  profiles:
    active: ${ACTIVE_PROFILE:native}
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
        overrides:
          example:
            animal: ${ds}{ANIMAL:${ANIMAL}}
            fruit: ${ds}{FRUIT:${FRUIT}}
            profile: ${ds}{PROFILE:${PROFILE}}
            branch: ${ds}{BRANCH:${BRANCH}}